### ISSUE TITLE
Missing "video_comment_edit" event subtype

### ISSUE THREAD

**Issue by nuqz** [fizvlad/vk-longpoll-bot-rb#4]
According to [groups events docs](https://vk.com/dev/groups_events) there should be also `video_comment_edit` event subtype, which is not currently available in the library. Bot lib throws an error, when I try to use this subtype.

**Comment by fizvlad** [comment]
[Fixed in v0.1.0](https://github.com/fizvlad/vk-longpoll-bot-rb/blob/v0.1.0/lib/vk_longpoll_bot/events.rb#L13)
